"""Report generation: markdown audit report, scored CSV, disavow
candidate file, and a JSON snapshot for month-over-month trend
comparison.
"""

import csv
import json
import os
from datetime import datetime, timezone


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def write_scored_csv(domains, path):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        wr = csv.writer(fh)
        wr.writerow(["domain", "score", "bucket", "linking_pages",
                     "target_pages", "dr", "opr", "origins", "markers",
                     "sample_url"])
        for rd in sorted(domains.values(), key=lambda r: -r.score):
            wr.writerow([
                rd.domain, rd.score, rd.bucket, rd.linking_pages,
                rd.target_pages,
                ("" if rd.dr is None else rd.dr),
                ("" if rd.opr is None else rd.opr),
                "|".join(sorted(rd.origins)),
                "; ".join(rd.markers),
                rd.sample_urls[0] if rd.sample_urls else "",
            ])


def write_disavow(domains, path):
    """Disavow CANDIDATES only. Review before any upload to Google."""
    toxic = [r for r in sorted(domains.values(), key=lambda r: -r.score)
             if r.bucket == "toxic"]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Disavow CANDIDATES generated by the Dedaub backlink audit\n")
        fh.write(f"# Generated: {_now()}\n")
        fh.write("# DO NOT upload this file to Google as-is.\n")
        fh.write("# 1. Review every domain below by hand.\n")
        fh.write("# 2. Delete any line you are not sure about.\n")
        fh.write("# 3. Only upload if there is a manual action in GSC or a\n")
        fh.write("#    confirmed negative-SEO attack. Google ignores most spam\n")
        fh.write("#    links on its own; a wrong disavow can hurt rankings.\n")
        fh.write("# Upload point: https://search.google.com/search-console/disavow-links\n\n")
        for rd in toxic:
            fh.write(f"# score {rd.score}: {'; '.join(rd.markers[:3])}\n")
            fh.write(f"domain:{rd.domain}\n")
    return len(toxic)


def write_snapshot(domains, summary, path):
    payload = {
        "generated": _now(),
        "summary": summary,
        "domains": {
            rd.domain: {
                "score": rd.score,
                "bucket": rd.bucket,
                "linking_pages": rd.linking_pages,
                "markers": rd.markers,
            } for rd in domains.values()
        },
    }
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)


def compare_snapshot(domains, prev_path):
    """Return (new_domains, lost_domains, escalated) vs a prior snapshot."""
    try:
        with open(prev_path, "r", encoding="utf-8") as fh:
            prev = json.load(fh).get("domains", {})
    except (OSError, ValueError):
        return None
    cur = set(domains.keys())
    old = set(prev.keys())
    escalated = [d for d in cur & old
                 if domains[d].bucket == "toxic" and prev[d].get("bucket") != "toxic"]
    return {
        "new": sorted(cur - old),
        "lost": sorted(old - cur),
        "escalated": sorted(escalated),
    }


def _md_table(rows, headers):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def write_report(domains, summary, path, trend=None, enriched=False):
    ranked = sorted(domains.values(), key=lambda r: -r.score)
    toxic = [r for r in ranked if r.bucket == "toxic"]
    review = [r for r in ranked if r.bucket == "review"]

    lines = []
    lines.append("# Backlink Audit Report: dedaub.com")
    lines.append(f"\nGenerated: {_now()}  ")
    lines.append(f"Enrichment: {'online (DNS, HTTP, Spamhaus, Open PageRank)' if enriched else 'offline signals only'}\n")

    lines.append("## Profile summary\n")
    lines.append(_md_table([[
        summary["total_domains"], summary["healthy"], summary["review"],
        summary["toxic"], f"{summary['toxic_share'] * 100:.1f}%",
        summary["profile_toxicity"],
    ]], ["Referring domains", "Healthy", "Review", "Toxic", "Toxic share", "Profile toxicity"]))
    lines.append("")
    lines.append("Bands follow the Semrush convention: HIGH above 10% toxic, "
                 "MEDIUM 3-10%, LOW below 3%.\n")

    if trend:
        lines.append("## Change since previous snapshot\n")
        lines.append(f"- New referring domains: {len(trend['new'])}"
                     + (f" ({', '.join(trend['new'][:10])}{'...' if len(trend['new']) > 10 else ''})" if trend['new'] else ""))
        lines.append(f"- Lost referring domains: {len(trend['lost'])}"
                     + (f" ({', '.join(trend['lost'][:10])}{'...' if len(trend['lost']) > 10 else ''})" if trend['lost'] else ""))
        lines.append(f"- Escalated to toxic: {len(trend['escalated'])}"
                     + (f" ({', '.join(trend['escalated'])})" if trend['escalated'] else ""))
        lines.append("")
        if len(trend["new"]) > 25:
            lines.append("NOTE: a sudden spike of new referring domains is the "
                         "main fingerprint of a negative-SEO campaign. "
                         "Cross-check the new domains' scores below.\n")

    lines.append(f"## Toxic domains ({len(toxic)})\n")
    if toxic:
        lines.append(_md_table(
            [[r.domain, r.score, r.linking_pages,
              "; ".join(r.markers[:4])] for r in toxic],
            ["Domain", "Score", "Linking pages", "Why"]))
    else:
        lines.append("None found.")
    lines.append("")

    lines.append(f"## Review queue ({len(review)})\n")
    if review:
        lines.append(_md_table(
            [[r.domain, r.score, r.linking_pages,
              "; ".join(r.markers[:3])] for r in review],
            ["Domain", "Score", "Linking pages", "Why"]))
    else:
        lines.append("None found.")
    lines.append("")

    lines.append("## Top healthy referring domains\n")
    healthy = [r for r in ranked if r.bucket == "healthy"]
    healthy_top = sorted(healthy, key=lambda r: -r.linking_pages)[:15]
    lines.append(_md_table(
        [[r.domain, r.linking_pages, r.target_pages,
          (f"{r.dr:.0f}" if r.dr is not None else "-"),
          (f"{r.opr:.1f}" if r.opr is not None else "-")] for r in healthy_top],
        ["Domain", "Linking pages", "Target pages", "DR", "Open PageRank"]))
    lines.append("")
    if any(r.dr is not None for r in ranked):
        lines.append("Authority data: Domain Rating by Ahrefs "
                     "(https://ahrefs.com/), free public endpoint.\n")

    lines.append("## What to do with this report\n")
    lines.append("1. Read the toxic table. Delete from the disavow candidate "
                 "file any domain that is actually fine.")
    lines.append("2. Do NOT upload the disavow file unless GSC shows a manual "
                 "action, or a negative-SEO spike is confirmed. Google "
                 "devalues most spam links automatically (Penguin 4.0).")
    lines.append("3. Move domains you trust into the whitelist in the config "
                 "so they never get flagged again.")
    lines.append("4. Keep the snapshot JSON: next month's run uses it to "
                 "detect new, lost and escalated domains.")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
